### ISSUE TITLE
SMF does not connect via PFCP

### ISSUE THREAD

**Issue by asantos-vk** [opennetworkinglab/aether-onramp#11]
Hello everyone!

I'm starting to use Aether to test some gNB solutions. At first I installed OnRamp, following the instructions here: https://docs.aetherproject.org/master/onramp/start.html

I changed some parameters to match my network: plmnid, mcc, mnc, imsi and dnn

After uploading k8s, 5gc and amp, I was finally able to connect gNB to authenticate a UE.

The problem is that it still hasn't authenticated. After some time trying to figure out what's going on, I noticed that there are some flaws in the SMF pod. Does anyone know how to solve this?

![image](https://github.com/opennetworkinglab/aether-onramp/assets/111907131/bbb06f4d-0736-495d-b4c0-0bfca9207315)

Edit: I couldn't find any endpoint with this address 10.42.112.112

**Comment by llpeterson** [comment]
Questions about AMF internals are probably best asked on Slack: https://onf-community.slack.com/
(either the aether-onramp or aether-dev channels).

**Comment by asantos-vk** [comment]
Thanks for your quick answer! @llpeterson, how can I join Slack? I don't have an account in any of those domains listed.

**Comment by llpeterson** [comment]
Send me an email (so I have your email), and I'll send an invitation. My email is the first three letters of my GitHub id, at opennetworking.org.
