### ISSUE TITLE
 UE does not get internet

### ISSUE THREAD

**Issue by Bhuvaneshnetcon** [opennetworkinglab/aether-onramp#13]
Hi,
   I have built aether-onramp successfully and did make aether-5gc-install but my UE quectel RM-520N-GL with 3GPP release 16 does not get internet. For your kind note upf is able to ping 8.8.8.8. Then my host linux network setting is set to be as follows:

ipv4-forwarding enable in sysctl
sudo iptables -t nat -A POSTROUTING -o dn-interface -j MASQUERADE
firewall is also disabled
Could you please help me to get internet to UE?

**Comment by llpeterson** [comment]
I have no specific experience with the Quectel RM-520N-GL. You might have better luck posting questions to the #aether-onramp channel on Slack. My only concrete suggestion to debugging the e2e data path is to capture the sequence of packet traces suggest here: https://docs.aetherproject.org/master/onramp/gnb.html#run-diagnostics.
