### ISSUE TITLE
Emulated RAN Tests Are Unstable

### ISSUE THREAD

**Issue by panitsasi** [opennetworkinglab/aether-onramp#32]
Hello, 

I am following the Quick Start Documentation to run the simple setup, but I am encountering issues when I run the command: make aether-gnbsim-run. Sometimes, only 1 or 2 UEs pass the tests while the others fail. Only once, all UEs pass the tests. I am attaching the following details for reference: 

The core network is running properly: 
![image](https://github.com/opennetworkinglab/aether-onramp/assets/70574362/9498d85e-c489-4ba5-b7e1-d8eaef51ea61)

The systemd-networkd is configured as expected, I am using 22.04 Ubuntu live server. The IPv6 is enabled to my interface. 
I configured the two files hosts.ini and main.yml correctly. 
![image](https://github.com/opennetworkinglab/aether-onramp/assets/70574362/4473a1ab-5791-471f-b4d5-06838ef537a3)

After running the gnb, these are the errors that I receive: 

![image](https://github.com/opennetworkinglab/aether-onramp/assets/70574362/ae944ee6-7f51-4bd1-96b6-f587e4073266)

![image](https://github.com/opennetworkinglab/aether-onramp/assets/70574362/768f51ee-1314-486d-a958-a86bb17582e7)

I tried to reset the core again and restart the gnb make aether-resetcore, but still the issues persisted. 

Regarding with this hint, "Another possibility is that you have multiple SD-Cores running in the same broadcast domain. This causes ARP to behave in unexpected ways, which interferes with OnRamp's ability to establish a route to the UPF pod", I think i only run one SD-Core in the machine. Can you let me know what command should i execute to observe this ? 

![image](https://github.com/opennetworkinglab/aether-onramp/assets/70574362/3926c01d-e0e2-4ed1-8110-eccaf2ff85cc)

**Comment by panitsasi** [comment]
Yes sure. 
[gnbsim.log](https://github.com/user-attachments/files/16182277/gnbsim.log)

Do i need in the main.yml file to delete the IP in ran_subnet and let it empty or it will not affect the installation? I tried both but it did not work.

**Comment by mbilal92** [comment]
ran_subnet should be in form of `ran_subnet: "172.20.0.0/16`

**Comment by panitsasi** [comment]
Yes, I changed it but the issue persisted. 

![image](https://github.com/user-attachments/assets/5b610cfa-a67f-4a6d-ace7-52625b3da718)

I attached the gnbsim.log file. 
[gnbsim.txt](https://github.com/user-attachments/files/16194678/gnbsim.txt)

**Comment by mbilal92** [comment]
can you try with 1 UE and then share the logs?

**Comment by mbilal92** [comment]
also are  you running [Emulated RAN](https://docs.aetherproject.org/master/onramp/gnbsim.html) or [Physical RAN](https://docs.aetherproject.org/master/onramp/gnb.html) ? and which vars file did you copy?

**Comment by panitsasi** [comment]
I am using the emulated RAN, and i followed the Quick Start Documentation. 
I re-installed all the project and now it works fine. 

![image](https://github.com/user-attachments/assets/584b2e74-a302-4a1e-aa0d-b9d33cfc7c9a)

Do you know why the gnbsim fails in the first tries ? Is it normal ?

**Comment by mbilal92** [comment]
Yes, that is expected, it does not fail, it's Ansible script waiting for gNBsim to run.
Closing this issue.
